#!/bin/bash

# Redirect all output to dev/null and disown the process

# Opens Edge (with Slack, Jira, dev server and GitHub) and IDEA
nohup microsoft-edge-stable \
    https://app.slack.com/client/T0PLLU9PS/C05KHUVU5T4 \
    http://localhost:3000/ \
    https://181506896476.signin.aws.amazon.com/console \
    https://nuelife.atlassian.net/jira/software/projects/NLS/boards/4 \
    >/dev/null 2>&1 &

nohup intellij-idea-ultimate-edition /home/chus/nue/nuelife-api/ \
    >/dev/null 2>&1 &

# Opens working directory and creates a new tmux session
cd /home/chus/nue/nuelife-api/
tmux new-session -d -s nue -n dev
tmux send-keys -t nue:dev '. ./start-frontend.sh' Enter
tmux split-window -v -t nue:dev
tmux send-keys -t nue:dev './start-containers.sh' Enter
tmux a
