#!/bin/bash

# Redirect all output to dev/null and disown the process

# Opens Edge (with Slack, Jira, dev server and GitHub) and IDEA
nohup microsoft-edge-stable \
    https://app.slack.com/client/T0PLLU9PS/C05KHUVU5T4 \
    http://localhost:5173/ \
    https://ensolvers.atlassian.net/jira/software/projects/HL/boards/22 \
    https://github.com/ensolvers/hirelens >/dev/null 2>&1 &
nohup intellij-idea-ultimate-edition /home/chus/hirelens/ >/dev/null 2>&1 &

# Opens working directory and creates a new tmux session
cd /home/chus/hirelens/
tmux new-session -d -s hirelens -n dev
tmux send-keys -t hirelens:dev './start-frontend.sh' Enter
tmux split-window -v -t hirelens:dev
tmux send-keys -t hirelens:dev 'docker-compose up -d' Enter
tmux a
