#!/bin/bash

# Check if there are enough arguments
if [ "$#" -lt 3 ]; then
    echo "Usage: vidconcat <file1> <file2> ... <filen> <output>"
    exit 1
fi

# Get the output file name
output="${@: -1}"
output="${output%.*}.mkv"

# Loops over the first n-1 files
for f in "${@:1:$#-1}"; do echo "file '$f'" >> vidconcatlist.txt; done

# Concatenate the videos
ffmpeg -f concat -safe 0 -i vidconcatlist.txt -c copy "$output"

# Remove the temporary file
rm -f vidconcatlist.txt
