import = [ "/home/chus/.config/alacritty/themes/themes/Kanagawa.toml",]

[env]
TERM = "alacritty"

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_title = true
opacity = 0.95
blur = true

[keyboard]
[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[window.dimensions]
columns = 80
lines = 24

[cursor.style]
blinking = "On"

[font.normal]
family = "CaskaydiaCove NF"
