import = ["/home/chus/.config/alacritty/themes/themes/vscode.dark.toml"]

[cursor.style]
blinking = "On"

[env]
TERM = "alacritty"

[font.normal]
family = "CaskaydiaCove NF"

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_title = true
opacity = 0.95

[window.dimensions]
columns = 80
lines = 24
