# Theme
include current-theme.conf

font_size 16
font_family JetBrainsMono Nerd Font Mono

hide_window_decorations yes

# My customization
url_style straight
placement_strategy top-left
inactive_text_alpha 0.6
remember_window_size no
start_as fullscreen
initial_window_width 80c
initial_window_height 24c
copy_on_select yes
map ctrl+c copy_or_interrupt

# Experimental
cursor_trail 3

# Input
touch_scroll_multiplier 10
